
language: python
# safelist
branches:
  only:
  - travis
before_install:
 - sudo apt-get update
 - sudo apt-get install python-gi
install:
 - pip install -r requirements.txt
script :
- pytest -v tests/
